// web/src/views/login.vue
<script setup lang="ts">
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";
import { ApiError } from "../api/users";
import { useAuth } from "../composables/useAuth";

const router = useRouter();
const { login } = useAuth();

const form = reactive({ email: "", password: "" });
const errorMessage = ref("");
const submitting = ref(false);

async function handleSubmit() {
  errorMessage.value = "";
  submitting.value = true;
  try {
    await login(form.email, form.password);
    const redirect = router.currentRoute.value.query.redirect;
    router.push(typeof redirect === "string" ? redirect : "/");
  } catch (err) {
    errorMessage.value = err instanceof ApiError ? err.message : "Falha ao entrar";
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <div class="flex min-h-[calc(100vh-140px)] items-center justify-center px-6 py-12">
    <div class="w-full max-w-sm">
      <div class="mb-8 flex flex-col items-center text-center">
        <img src="/images/favicon.svg" alt="" class="h-12 w-12" />
        <h1 class="mt-4 font-display text-2xl font-bold text-ink-900">Bem-vindo de volta</h1>
        <p class="mt-1 text-sm text-ink-500">Acesse sua conta</p>
      </div>

      <div class="rounded-3xl border border-ink-200/70 bg-white p-8 shadow-xl shadow-ink-900/5">
        <form class="flex flex-col gap-4" @submit.prevent="handleSubmit">
          <label class="flex flex-col gap-1.5">
            <span class="text-sm font-medium text-ink-700">E-mail</span>
            <input
              v-model="form.email"
              type="email"
              placeholder="voce@exemplo.com"
              required
              autocomplete="username"
              class="rounded-xl border border-ink-200 bg-ink-50/50 px-3.5 py-2.5 text-sm text-ink-900 outline-none transition placeholder:text-ink-400 focus:border-brand-400 focus:bg-white focus:ring-4 focus:ring-brand-100"
            />
          </label>
          <label class="flex flex-col gap-1.5">
            <span class="text-sm font-medium text-ink-700">Senha</span>
            <input
              v-model="form.password"
              type="password"
              placeholder="••••••••"
              required
              autocomplete="current-password"
              class="rounded-xl border border-ink-200 bg-ink-50/50 px-3.5 py-2.5 text-sm text-ink-900 outline-none transition placeholder:text-ink-400 focus:border-brand-400 focus:bg-white focus:ring-4 focus:ring-brand-100"
            />
          </label>
          <button
            type="submit"
            :disabled="submitting"
            class="mt-2 rounded-full bg-ink-900 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-ink-900/10 transition hover:bg-ink-800 disabled:opacity-50"
          >
            {{ submitting ? "Entrando..." : "Entrar" }}
          </button>
        </form>

        <p v-if="errorMessage" class="mt-4 rounded-xl bg-coral-50 px-3 py-2 text-sm text-coral-700">
          {{ errorMessage }}
        </p>

        <div class="mt-6 flex items-center gap-3 text-xs text-ink-400">
          <span class="h-px flex-1 bg-ink-200"></span>
          ou
          <span class="h-px flex-1 bg-ink-200"></span>
        </div>

        <a
          href="/api/auth/google/login"
          class="mt-4 flex items-center justify-center gap-2 rounded-full border border-ink-200 bg-white px-4 py-2.5 text-sm font-semibold text-ink-700 shadow-sm transition hover:bg-ink-100"
        >
          Continuar com Google
        </a>

        <p class="mt-6 text-center text-sm text-ink-500">
          Não tem conta?
          <RouterLink to="/register" class="font-semibold text-brand-700 hover:text-brand-800">
            Cadastre-se
          </RouterLink>
        </p>
      </div>
    </div>
  </div>
</template>

// src/app/login/page.tsx
"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { signIn } from "@/lib/auth-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

function LoginForm() {
	const router = useRouter();
	const searchParams = useSearchParams();
	const next = searchParams.get("next") ?? "/";

	const [email, setEmail] = useState("");
	const [password, setPassword] = useState("");
	const [error, setError] = useState<string | null>(null);
	const [loading, setLoading] = useState(false);

	async function handleSubmit(e: React.FormEvent) {
		e.preventDefault();
		setLoading(true);
		setError(null);

		const { error } = await signIn.email({ email, password });

		if (error) {
			setError("E-mail ou senha incorretos.");
			setLoading(false);
			return;
		}

		router.push(next);
		router.refresh();
	}

	return (
		<div className="min-h-screen bg-zinc-950 flex items-center justify-center p-4">
			<div className="w-full max-w-sm">
				{/* Logo */}
				<div className="flex items-center justify-center gap-2 mb-8">
					<div className="h-10 w-10 rounded-xl bg-indigo-600 flex items-center justify-center">
						<span className="text-lg font-bold text-white">R</span>
					</div>
					<div>
						<span className="text-2xl font-bold text-white">ReConta</span>
						<span className="text-sm text-zinc-400">.app</span>
					</div>
				</div>

				<div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8">
					<h1 className="text-xl font-semibold text-zinc-100 mb-1">Entrar</h1>
					<p className="text-sm text-zinc-400 mb-6">
						Acesse sua conta para continuar
					</p>

					<form onSubmit={handleSubmit} className="space-y-4">
						<div>
							<Label htmlFor="email">E-mail</Label>
							<Input
								id="email"
								type="email"
								placeholder="seu@email.com"
								value={email}
								onChange={(e) => setEmail(e.target.value)}
								required
								autoComplete="email"
								className="mt-1"
							/>
						</div>

						<div>
							<Label htmlFor="password">Senha</Label>
							<Input
								id="password"
								type="password"
								placeholder="••••••••"
								value={password}
								onChange={(e) => setPassword(e.target.value)}
								required
								autoComplete="current-password"
								className="mt-1"
							/>
						</div>

						{error && (
							<p className="text-sm text-red-400 bg-red-900/20 border border-red-800/30 rounded-lg px-3 py-2">
								{error}
							</p>
						)}

						<Button type="submit" className="w-full" disabled={loading}>
							{loading ? "Entrando..." : "Entrar"}
						</Button>
					</form>

					<p className="text-center text-sm text-zinc-500 mt-6">
						Não tem uma conta?{" "}
						<Link href="/cadastro" className="text-indigo-400 hover:underline">
							Criar conta
						</Link>
					</p>
				</div>
			</div>
		</div>
	);
}

export default function LoginPage() {
	return (
		<Suspense>
			<LoginForm />
		</Suspense>
	);
}
